---
- hosts: webserver
  become: true
  become_user: root

  tasks:
  - name: Install Softwares
    yum:
      name: "{{item}}"
      state: present
    loop:
      - docker
      - git
  - name: Clone the repository
    git:
      repo:
        https://github.com/amarpallai/projCert.git
      dest:
          /tmp/proj1
  - name: Start docker
    service:
      name:
        docker
      state:
        started
  - name: Build dockerfile
    command: docker build -t myimage:1 .
    args:
      chdir: /tmp/proj1/website

