---
- hosts: webserver
  become: true
  become_user: root

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: Deploy php file
    copy:
      src: content/home.php
      dest: /var/www/html
    notify: Restart httpd
  handlers:
    - name: Restart the httpd
      service:
        name: httpd
        state: restarted
