---
- hosts: webserver
  become: true
  become_user: root

  tasks:
  - name: Install Softwares
    yum:
      name: "{{item}}"
      state: present
    loop:
      - docker
      - git
  - name: Clone the repository
    git:
      repo:
        https://github.com/amarpallai/projCert.git
      dest:
          /tmp/proj1
  - name: Start docker
    service:
      name:
        docker
      state:
        started
  - name: Build dockerfile
    command: docker build -t myphp:1 .
    args:
      chdir: /tmp/proj1/website
      
  - name: Running a container
    command:
      docker run --name myphpcon -d -P myphp:1

