---
- hosts: webserver
  become: true
  become_user: root

  tasks:
  - name: Install Softwares
    yum:
      name: "{{item}}"
      state: present
    loop:
      - docker
      - git
  - name: Clone the repository
    git:
      repo:
        https://github.com/amarpallai/projCert.git
      dest:
          /hpme/ec2-user/proj1
  - name: Start docker
    service:
      name:
        docker
      state:
        started
  - name: Deploy the dockerfile
    command:
      chdir:
        /home/ec2-user/proj1 docker build -t myphp:1 .
  - name: Running a container
    command:
      docker run --name myphpcon -d -P myphp:1
